$(document).ready(function(){
	
	
	$("#firstPage").click(function(){
		hideNavContents();
		 $("#customerLoginName").val("");
		  $("#customerLoginPassword").val("");
		  $("#restaurantUserName").val("");
		  $("#restaurantPassword").val("");
		  $("#txtAdminLoginUsername").val("");
		  $("#txtAdminLoginPassword").val("");
		$("#firstPageContent").show();
	});
	
	$("#secondPage").click(function(){
		hideNavContents();
		 $("#customerLoginName").val("");
		  $("#customerLoginPassword").val("");
		  $("#restaurantUserName").val("");
		  $("#restaurantPassword").val("");
		  $("#txtAdminLoginUsername").val("");
		  $("#txtAdminLoginPassword").val("");
		$("#courier-booking").show();
	});
	$("#btncourierbookinglinks").click(function(){
		hideNavContents();
		 $("#customerLoginName").val("");
		  $("#customerLoginPassword").val("");
		  $("#restaurantUserName").val("");
		  $("#restaurantPassword").val("");
		  $("#txtAdminLoginUsername").val("");
		  $("#txtAdminLoginPassword").val("");
		$("#courier-booking").show();
		$("#courier-booking").show();
	});
	$("#btngivelinkrestaurant").click(function(){
		hideNavContents();
		 $("#customerLoginName").val("");
		  $("#customerLoginPassword").val("");
		  $("#restaurantUserName").val("");
		  $("#restaurantPassword").val("");
		  $("#txtAdminLoginUsername").val("");
		  $("#txtAdminLoginPassword").val("");
		$("#restaurant-delivery-boy-booking").show();
	});
	$("#thirdPage").click(function(){
		hideNavContents();
		 $("#customerLoginName").val("");
		  $("#customerLoginPassword").val("");
		  $("#restaurantUserName").val("");
		  $("#restaurantPassword").val("");
		  $("#txtAdminLoginUsername").val("");
		  $("#txtAdminLoginPassword").val("");
		$("#restaurant-delivery-boy-booking").show();
	});
	
	$("#fourthPage").click(function(){
		hideNavContents();
		 $("#customerLoginName").val("");
		  $("#customerLoginPassword").val("");
		  $("#restaurantUserName").val("");
		  $("#restaurantPassword").val("");
		  $("#txtAdminLoginUsername").val("");
		  $("#txtAdminLoginPassword").val("");
		$("#admin").show().slideDown();
	});
	
	$("#btnprivacyPolicy").click(function(){
		hideNavContents();
		 $("#customerLoginName").val("");
		  $("#customerLoginPassword").val("");
		  $("#restaurantUserName").val("");
		  $("#restaurantPassword").val("");
		  $("#txtAdminLoginUsername").val("");
		  $("#txtAdminLoginPassword").val("");
		$("#privacyPolicy").show();
	});
	
	$("#btndisclaimerPolicy").click(function(){
		hideNavContents();
		 $("#customerLoginName").val("");
		  $("#customerLoginPassword").val("");
		  $("#restaurantUserName").val("");
		  $("#restaurantPassword").val("");
		  $("#txtAdminLoginUsername").val("");
		  $("#txtAdminLoginPassword").val("");
		$("#disclaimerPolicy").show();
	});
	$("#btncancellationPolicy").click(function(){
		hideNavContents();
		 $("#customerLoginName").val("");
		  $("#customerLoginPassword").val("");
		  $("#restaurantUserName").val("");
		  $("#restaurantPassword").val("");
		  $("#txtAdminLoginUsername").val("");
		  $("#txtAdminLoginPassword").val("");
		$("#cancellationPolicy").show();
	});
	$("#btnshippingPolicy").click(function(){
		hideNavContents();
		 $("#customerLoginName").val("");
		  $("#customerLoginPassword").val("");
		  $("#restaurantUserName").val("");
		  $("#restaurantPassword").val("");
		  $("#txtAdminLoginUsername").val("");
		  $("#txtAdminLoginPassword").val("");
		$("#shippingPolicy").show();
	});
	$("#btnSiteMap").click(function(){
		hideNavContents();
		 $("#customerLoginName").val("");
		  $("#customerLoginPassword").val("");
		  $("#restaurantUserName").val("");
		  $("#restaurantPassword").val("");
		  $("#txtAdminLoginUsername").val("");
		  $("#txtAdminLoginPassword").val("");
		$("#flowChart").show();
	});
	$("#btnConditions").click(function(){
		hideNavContents();
		 $("#customerLoginName").val("");
		  $("#customerLoginPassword").val("");
		  $("#restaurantUserName").val("");
		  $("#restaurantPassword").val("");
		  $("#txtAdminLoginUsername").val("");
		  $("#txtAdminLoginPassword").val("");
		$("#terms").show();
	});
	
	$("#btnAboutUs").click(function(){
		hideNavContents();
		 $("#customerLoginName").val("");
		  $("#customerLoginPassword").val("");
		  $("#restaurantUserName").val("");
		  $("#restaurantPassword").val("");
		  $("#txtAdminLoginUsername").val("");
		  $("#txtAdminLoginPassword").val("");
		$("#aboutUs").show();
	});
	$("#btnOurService").click(function(){
		hideNavContents();
		 $("#customerLoginName").val("");
		  $("#customerLoginPassword").val("");
		  $("#restaurantUserName").val("");
		  $("#restaurantPassword").val("");
		  $("#txtAdminLoginUsername").val("");
		  $("#txtAdminLoginPassword").val("");
		$("#services").show();
	});
	$("#btnContactUs").click(function(){
		hideNavContents();
		 $("#customerLoginName").val("");
		  $("#customerLoginPassword").val("");
		  $("#restaurantUserName").val("");
		  $("#restaurantPassword").val("");
		  $("#txtAdminLoginUsername").val("");
		  $("#txtAdminLoginPassword").val("");
		$("#contact").show();
	});
	
});

function hideNavContents(){
	
	 $("#firstPageContent").hide();
	$("#courier-booking").hide();
	$("#restaurant-delivery-boy-booking").hide();
	$("#admin").hide();
	$("#privacyPolicy").hide();
	$("#disclaimerPolicy").hide();
	$("#cancellationPolicy").hide();
	$("#shippingPolicy").hide();
	$("#flowChart").hide();
	$("#terms").hide();
	$("#aboutUs").hide();
	$("#services").hide();
	$("#contact").hide();
	
}

